### ISSUE TITLE
Doesn't actually work, can't serve video

### ISSUE THREAD

**Issue by milankragujevic** [iovis9/dlnast#1]
Just wanted to let you know, this package doesn't actually work, it can't serve a video and the TV fails with Unsupported video, however I can't even play it with the browser because it doesn't serve the video properly...

**Comment by iovis9** [comment]
Ugh, gotta give this package some love I haven't used it for a long time. Thanks for the feedback!

**Comment by iovis9** [comment]
I'm testing it and it works. I'm currently doing some refactoring but could you give me an example of a file that is not working and the actual error?
